### ISSUE TITLE
chapter7  .. CRDT ?

### ISSUE THREAD

**Issue by boboyada** [PacktPublishing/Scala-High-Performance-Programming#1]
def update(
    change: CounterUpdate): (StateBasedGCounter, GCounterState) = {
    (new StateBasedGCounter(uid, count + change.i, otherCounters),
      GCounterState(uid, count)) //note here
  }
==>
  def update(
    change: CounterUpdate): (StateBasedGCounter, GCounterState) = {
    (new StateBasedGCounter(uid, count + change.i, otherCounters),
      GCounterState(uid, count+ change.i))  //note here 
  }

or
GCounterState(uid, count))   
=>
GCounterState(uid, count+ change.i)) 

??

**Comment by ManikandanKurup-Packt** [comment]
Hi, please reopen if the issue still persists.
